"""Optional HA-aligned entities (disabled by default via entity_groups)."""

from __future__ import annotations

from typing import Any

from entity_groups import (
    GROUP_ADVANCED_CONTROLS,
    GROUP_BINARY,
    GROUP_DIAGNOSTICS,
    GROUP_ENERGY_DETAIL,
    GROUP_ENERGY_STATISTICS,
    GROUP_EV_CHARGER,
    GROUP_HES,
    GROUP_POWER_FLOWS,
    GROUP_POWER_PANEL,
    GROUP_PPS,
    GROUP_SITE_PRICE,
    GROUP_SMARTPLUG,
    GROUP_SYSTEM_OVERVIEW,
)
SOLARBANK = "solarbank"
SYSTEM = "system"
SITE = "site"
COMBINER = "combiner_box"
SMARTMETER = "smartmeter"
SMARTPLUG = "smartplug"

# --- Power flow sensors (signed / directional) ---
EXTENDED_SENSOR_ENTITIES: list[dict[str, Any]] = [
    {
        "id": "solar_power_total",
        "keys": ["solar_power_total", "photovoltaic_power_total"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, SYSTEM, SITE, COMBINER],
        "groups": [GROUP_POWER_FLOWS],
        "nested": True,
    },
    {
        "id": "grid_power_signed",
        "keys": ["grid_power_signed", "grid_import_power_signed"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, SYSTEM, SITE, SMARTMETER],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "battery_power_signed",
        "keys": ["battery_power_signed", "bat_power_signed"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, SYSTEM, COMBINER],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "home_load_power",
        "keys": ["home_load_power", "home_demand_total"],
        "unit": "W",
        "role": "value.power",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_POWER_FLOWS, GROUP_SYSTEM_OVERVIEW],
        "nested": True,
    },
    {
        "id": "pv_to_home_power",
        "keys": ["pv_to_home_power", "solar_to_home_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, SYSTEM, SITE],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "pv_to_battery_power",
        "keys": ["pv_to_battery_power", "solar_to_battery_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, SYSTEM, SITE],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "battery_to_home_power",
        "keys": ["battery_to_home_power", "bat_to_home_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, SYSTEM, SITE],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "grid_to_battery_power",
        "keys": ["grid_to_battery_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, SYSTEM, SITE],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "photovoltaic_to_grid_power",
        "keys": ["photovoltaic_to_grid_power", "solar_to_grid_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, SYSTEM, SITE, SMARTMETER],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "ac_input_power",
        "keys": ["ac_input_power", "ac_input_power_total"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, COMBINER],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "ac_output_power",
        "keys": ["ac_output_power", "ac_output_power_total"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, COMBINER],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "bat_charge_power",
        "keys": ["bat_charge_power", "battery_charge_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "bat_discharge_power",
        "keys": ["bat_discharge_power", "battery_discharge_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "heating_power",
        "keys": ["heating_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK],
        "groups": [GROUP_POWER_FLOWS],
    },
    # Diagnostics
    {
        "id": "status_desc",
        "keys": ["status_desc"],
        "role": "text",
        "types": [SOLARBANK, COMBINER, SMARTMETER, SMARTPLUG],
        "groups": [GROUP_DIAGNOSTICS],
    },
    {
        "id": "charging_status_desc",
        "keys": ["charging_status_desc"],
        "role": "text",
        "types": [SOLARBANK],
        "groups": [GROUP_DIAGNOSTICS],
    },
    {
        "id": "sw_version",
        "keys": ["sw_version", "main_sw_version"],
        "role": "text",
        "types": [SOLARBANK, COMBINER, SMARTMETER, SMARTPLUG],
        "groups": [GROUP_DIAGNOSTICS],
    },
    {
        "id": "device_temperature",
        "keys": ["temperature", "device_temperature"],
        "unit": "°C",
        "role": "value.temperature",
        "types": [SOLARBANK, COMBINER],
        "groups": [GROUP_DIAGNOSTICS],
    },
    {
        "id": "err_code",
        "keys": ["err_code", "error_code"],
        "role": "value",
        "types": [SOLARBANK, COMBINER],
        "groups": [GROUP_DIAGNOSTICS],
    },
    {
        "id": "device_tag",
        "keys": ["tag", "device_tag"],
        "role": "text",
        "types": [SOLARBANK, COMBINER, SMARTMETER],
        "groups": [GROUP_DIAGNOSTICS],
    },
    {
        "id": "inverter_info",
        "keys": ["inverter_info", "inverter_brand"],
        "role": "text",
        "types": [SOLARBANK, SYSTEM, SITE],
        "groups": [GROUP_DIAGNOSTICS],
    },
    # Binary-style indicators (stored as boolean states)
    {
        "id": "wifi_connection",
        "keys": ["wifi_connection", "wifi_online", "wifi_state"],
        "role": "indicator.reachability",
        "types": [SOLARBANK, COMBINER, SMARTMETER, SMARTPLUG],
        "groups": [GROUP_BINARY],
        "kind": "boolean",
    },
    {
        "id": "mqtt_connection",
        "keys": ["mqtt_connection", "mqtt_online"],
        "role": "indicator.reachability",
        "types": [SOLARBANK, COMBINER],
        "groups": [GROUP_BINARY],
        "kind": "boolean",
    },
    {
        "id": "ota_update_available",
        "keys": ["ota_update", "ota_upgrade"],
        "role": "indicator",
        "types": [SOLARBANK, COMBINER, SMARTPLUG],
        "groups": [GROUP_BINARY],
        "kind": "boolean",
    },
    {
        "id": "heating_active",
        "keys": ["heating", "heating_status"],
        "role": "indicator",
        "types": [SOLARBANK],
        "groups": [GROUP_BINARY],
        "kind": "boolean",
    },
    {
        "id": "protection_active",
        "keys": ["protection_status", "protect_status"],
        "role": "indicator",
        "types": [SOLARBANK],
        "groups": [GROUP_BINARY],
        "kind": "boolean",
    },
    # System overview
    {
        "id": "solarbank_list",
        "keys": ["solarbank_list"],
        "role": "text",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_SYSTEM_OVERVIEW],
    },
    {
        "id": "other_loads_power",
        "keys": ["other_loads_power", "other_load_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_SYSTEM_OVERVIEW],
        "nested": True,
    },
    {
        "id": "smart_plugs_power",
        "keys": ["smart_plugs_power", "smartplug_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_SYSTEM_OVERVIEW],
        "nested": True,
    },
    # Site price (read-only sensors when enabled)
    {
        "id": "dynamic_price_total",
        "keys": ["dynamic_price_total", "price_total"],
        "unit": "€/kWh",
        "role": "value",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_SITE_PRICE],
        "nested": True,
    },
    {
        "id": "spot_price_mwh",
        "keys": ["spot_price_mwh", "spot_price"],
        "unit": "€/MWh",
        "role": "value",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_SITE_PRICE],
        "nested": True,
    },
    # PPS basics (read)
    {
        "id": "pps_battery_soc",
        "keys": ["battery_soc", "state_of_charge"],
        "unit": "%",
        "role": "value.battery",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },
    {
        "id": "pps_input_power",
        "keys": ["input_power", "ac_input_power"],
        "unit": "W",
        "role": "value.power",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },
    {
        "id": "pps_output_power",
        "keys": ["output_power", "ac_output_power"],
        "unit": "W",
        "role": "value.power",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },
    # Smart plug
    {
        "id": "smartplug_power",
        "keys": ["power", "output_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SMARTPLUG],
        "groups": [GROUP_SMARTPLUG],
    },
    {
        "id": "smartplug_energy_today",
        "keys": ["energy_today", "today_energy"],
        "unit": "kWh",
        "role": "value.energy",
        "types": [SMARTPLUG],
        "groups": [GROUP_SMARTPLUG, GROUP_ENERGY_DETAIL],
    },
    # EV charger (read)
    {
        "id": "evcharger_power",
        "keys": ["output_power", "charge_power"],
        "unit": "W",
        "role": "value.power",
        "types": ["ev_charger", "charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "evcharger_status_desc",
        "keys": ["status_desc", "work_status_desc"],
        "role": "text",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_mode_status",
        "keys": ["ev_charger_mode_status"],
        "role": "value.mode",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    # HES / power panel (minimal)
    {
        "id": "hes_grid_power",
        "keys": ["grid_power", "grid_import_power"],
        "unit": "W",
        "role": "value.power",
        "types": ["hes", "home_backup"],
        "groups": [GROUP_HES],
    },
    {
        "id": "powerpanel_avg_power",
        "keys": ["avg_power", "average_power"],
        "unit": "W",
        "role": "value.power",
        "types": ["powerpanel"],
        "groups": [GROUP_POWER_PANEL],
    },
]

EXTENDED_CONTROL_ENTITIES: list[dict[str, Any]] = [
    {
        "id": "ev_charger_mode",
        "keys": ["ev_charger_mode"],
        "role": "value.mode",
        "types": ["ev_charger"],
        "control": "ev_charger_mode",
        "kind": "list",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "preset_discharge_priority",
        "keys": ["preset_discharge_priority", "priority_discharge_switch"],
        "role": "switch",
        "types": [SOLARBANK, COMBINER],
        "control": "preset_discharge_priority",
        "groups": [GROUP_ADVANCED_CONTROLS],
    },
    {
        "id": "preset_backup_option",
        "keys": ["preset_backup_option", "backup_option"],
        "role": "switch",
        "types": [SOLARBANK, COMBINER],
        "control": "preset_backup_option",
        "groups": [GROUP_ADVANCED_CONTROLS],
    },
    {
        "id": "preset_charge_priority",
        "keys": ["preset_charge_priority", "charge_priority", "default_charge_priority"],
        "role": "level",
        "types": [SOLARBANK, COMBINER],
        "control": "preset_charge_priority",
        "min": 0,
        "max": 100,
        "groups": [GROUP_ADVANCED_CONTROLS],
    },
    {
        "id": "preset_device_output_power",
        "keys": ["preset_device_output_power", "device_output_power"],
        "role": "level.power",
        "types": [SOLARBANK],
        "control": "preset_device_output_power",
        "min": 0,
        "max": 1200,
        "groups": [GROUP_ADVANCED_CONTROLS],
    },
    {
        "id": "max_soc",
        "keys": ["max_soc", "soc_max"],
        "role": "level.battery",
        "types": [SOLARBANK, COMBINER],
        "control": "max_soc",
        "min": 0,
        "max": 100,
        "groups": [GROUP_ADVANCED_CONTROLS],
    },
    {
        "id": "backup_soc",
        "keys": ["backup_soc", "soc_backup"],
        "role": "level.battery",
        "types": [SOLARBANK, COMBINER],
        "control": "backup_soc",
        "min": 0,
        "max": 100,
        "groups": [GROUP_ADVANCED_CONTROLS],
    },
    {
        "id": "auto_upgrade",
        "keys": ["auto_upgrade", "auto_upgrade_switch"],
        "role": "switch",
        "types": [SOLARBANK, COMBINER, SMARTPLUG],
        "control": "auto_upgrade",
        "groups": [GROUP_ADVANCED_CONTROLS],
    },
    # PPS switches (MQTT when available)
    {
        "id": "ac_output_power_switch",
        "keys": ["ac_output_power_switch", "ac_output_switch"],
        "role": "switch",
        "types": ["pps", "solarbank_pps"],
        "control": "ac_output_power_switch",
        "groups": [GROUP_PPS],
    },
    {
        "id": "ac_fast_charge_switch_pps",
        "keys": ["ac_charge_switch", "ac_fast_charge_switch"],
        "role": "switch",
        "types": ["pps"],
        "control": "ac_fast_charge_switch",
        "groups": [GROUP_PPS],
    },
]

# Extra daily energy statistics (energy_detail group)
EXTENDED_ENERGY_STATISTICS: list[dict[str, Any]] = [
    {
        "id": "daily_solar_to_grid",
        "keys": ["solar_to_grid"],
        "unit": "kWh",
        "types": [SYSTEM, SITE, SOLARBANK, COMBINER],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_solar_production_pv1",
        "keys": ["solar_production_pv1", "pv1_production"],
        "unit": "kWh",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_solar_production_pv2",
        "keys": ["solar_production_pv2", "pv2_production"],
        "unit": "kWh",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_solar_production_pv3",
        "keys": ["solar_production_pv3", "pv3_production"],
        "unit": "kWh",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_solar_production_pv4",
        "keys": ["solar_production_pv4", "pv4_production"],
        "unit": "kWh",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_solar_production_inverter",
        "keys": ["solar_production_inverter", "inverter_production"],
        "unit": "kWh",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_solar_share",
        "keys": ["solar_share"],
        "unit": "%",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_battery_share",
        "keys": ["battery_share"],
        "unit": "%",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_grid_share",
        "keys": ["grid_share"],
        "unit": "%",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_ac_socket",
        "keys": ["ac_socket", "ac_socket_energy"],
        "unit": "kWh",
        "types": [SYSTEM, SITE, SOLARBANK],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_smartplugs_total",
        "keys": ["smartplugs_total", "smartplug_total"],
        "unit": "kWh",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL, GROUP_SMARTPLUG],
    },
]

EXTENDED_STATISTICS_LABELS_DE: dict[str, str] = {
    "daily_solar_to_grid": "Solar → Netz (heute)",
    "daily_solar_production_pv1": "PV1 Ertrag (heute)",
    "daily_solar_production_pv2": "PV2 Ertrag (heute)",
    "daily_solar_production_pv3": "PV3 Ertrag (heute)",
    "daily_solar_production_pv4": "PV4 Ertrag (heute)",
    "daily_solar_production_inverter": "WR Ertrag (heute)",
    "daily_solar_share": "Solar-Anteil (heute)",
    "daily_battery_share": "Batterie-Anteil (heute)",
    "daily_grid_share": "Netz-Anteil (heute)",
    "daily_ac_socket": "AC-Steckdose (heute)",
    "daily_smartplugs_total": "Steckdosen gesamt (heute)",
}
