"""Optional HA-aligned entities (disabled by default via entity_groups)."""

from __future__ import annotations

from typing import Any

from entity_groups import (
    GROUP_ADVANCED_CONTROLS,
    GROUP_BINARY,
    GROUP_DIAGNOSTICS,
    GROUP_ENERGY_DETAIL,
    GROUP_ENERGY_STATISTICS,
    GROUP_EV_CHARGER,
    GROUP_HES,
    GROUP_POWER_FLOWS,
    GROUP_POWER_PANEL,
    GROUP_PPS,
    GROUP_SITE_PRICE,
    GROUP_SMARTPLUG,
    GROUP_SYSTEM_OVERVIEW,
)
SOLARBANK = "solarbank"
SYSTEM = "system"
SITE = "site"
COMBINER = "combiner_box"
SMARTMETER = "smartmeter"
SMARTPLUG = "smartplug"

# --- Power flow sensors (signed / directional) ---
EXTENDED_SENSOR_ENTITIES: list[dict[str, Any]] = [
    {
        "id": "solar_power_total",
        "keys": ["solar_power_total", "photovoltaic_power_total"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, SYSTEM, SITE, COMBINER],
        "groups": [GROUP_POWER_FLOWS],
        "nested": True,
    },
    {
        "id": "grid_power_signed",
        "keys": ["grid_power_signed", "grid_import_power_signed"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, SYSTEM, SITE, SMARTMETER],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "battery_power_signed",
        "keys": ["battery_power_signed", "bat_power_signed"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, SYSTEM, COMBINER],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "home_load_power",
        "keys": ["home_load_power", "home_demand_total"],
        "unit": "W",
        "role": "value.power",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_POWER_FLOWS, GROUP_SYSTEM_OVERVIEW],
        "nested": True,
    },
    {
        "id": "pv_to_home_power",
        "keys": ["pv_to_home_power", "solar_to_home_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, SYSTEM, SITE],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "pv_to_battery_power",
        "keys": ["pv_to_battery_power", "solar_to_battery_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, SYSTEM, SITE],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "battery_to_home_power",
        "keys": ["battery_to_home_power", "bat_to_home_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, SYSTEM, SITE],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "grid_to_battery_power",
        "keys": ["grid_to_battery_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, SYSTEM, SITE],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "photovoltaic_to_grid_power",
        "keys": ["photovoltaic_to_grid_power", "solar_to_grid_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, SYSTEM, SITE, SMARTMETER],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "ac_input_power",
        "keys": ["ac_input_power", "ac_input_power_total"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, COMBINER],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "ac_output_power",
        "keys": ["ac_output_power", "ac_output_power_total"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK, COMBINER],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "bat_charge_power",
        "keys": ["bat_charge_power", "battery_charge_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "bat_discharge_power",
        "keys": ["bat_discharge_power", "battery_discharge_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK],
        "groups": [GROUP_POWER_FLOWS],
    },
    {
        "id": "heating_power",
        "keys": ["heating_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SOLARBANK],
        "groups": [GROUP_POWER_FLOWS],
    },
    # Diagnostics
    {
        "id": "status_desc",
        "keys": ["status_desc"],
        "role": "text",
        "types": [SOLARBANK, COMBINER, SMARTMETER, SMARTPLUG],
        "groups": [GROUP_DIAGNOSTICS],
    },
    {
        "id": "charging_status_desc",
        "keys": ["charging_status_desc"],
        "role": "text",
        "types": [SOLARBANK],
        "groups": [GROUP_DIAGNOSTICS],
    },
    {
        "id": "sw_version",
        "keys": ["sw_version", "main_sw_version"],
        "role": "text",
        "types": [SOLARBANK, COMBINER, SMARTMETER, SMARTPLUG],
        "groups": [GROUP_DIAGNOSTICS],
    },
    {
        "id": "device_temperature",
        "keys": ["temperature", "device_temperature"],
        "unit": "°C",
        "role": "value.temperature",
        "types": [SOLARBANK, COMBINER],
        "groups": [GROUP_DIAGNOSTICS],
    },
    {
        "id": "err_code",
        "keys": ["err_code", "error_code"],
        "role": "value",
        "types": [SOLARBANK, COMBINER],
        "groups": [GROUP_DIAGNOSTICS],
    },
    {
        "id": "device_tag",
        "keys": ["tag", "device_tag"],
        "role": "text",
        "types": [SOLARBANK, COMBINER, SMARTMETER],
        "groups": [GROUP_DIAGNOSTICS],
    },
    {
        "id": "inverter_info",
        "keys": ["inverter_info", "inverter_brand"],
        "role": "text",
        "types": [SOLARBANK, SYSTEM, SITE],
        "groups": [GROUP_DIAGNOSTICS],
    },
    # Binary-style indicators (stored as boolean states)
    {
        "id": "wifi_connection",
        "keys": ["wifi_connection", "wifi_online", "wifi_state"],
        "role": "indicator.reachability",
        "types": [SOLARBANK, COMBINER, SMARTMETER, SMARTPLUG],
        "groups": [GROUP_BINARY],
        "kind": "boolean",
    },
    {
        "id": "mqtt_connection",
        "keys": ["mqtt_connection", "mqtt_online"],
        "role": "indicator.reachability",
        "types": [SOLARBANK, COMBINER],
        "groups": [GROUP_BINARY],
        "kind": "boolean",
    },
    {
        "id": "ota_update_available",
        "keys": ["ota_update", "ota_upgrade"],
        "role": "indicator",
        "types": [SOLARBANK, COMBINER, SMARTPLUG],
        "groups": [GROUP_BINARY],
        "kind": "boolean",
    },
    {
        "id": "heating_active",
        "keys": ["heating", "heating_status"],
        "role": "indicator",
        "types": [SOLARBANK],
        "groups": [GROUP_BINARY],
        "kind": "boolean",
    },
    {
        "id": "protection_active",
        "keys": ["protection_status", "protect_status"],
        "role": "indicator",
        "types": [SOLARBANK],
        "groups": [GROUP_BINARY],
        "kind": "boolean",
    },
    # System overview
    {
        "id": "solarbank_list",
        "keys": ["solarbank_list"],
        "role": "text",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_SYSTEM_OVERVIEW],
    },
    {
        "id": "other_loads_power",
        "keys": ["other_loads_power", "other_load_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_SYSTEM_OVERVIEW],
        "nested": True,
    },
    {
        "id": "smart_plugs_power",
        "keys": ["smart_plugs_power", "smartplug_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_SYSTEM_OVERVIEW],
        "nested": True,
    },
    # Site price (read-only sensors when enabled)
    {
        "id": "dynamic_price_total",
        "keys": ["dynamic_price_total", "price_total"],
        "unit": "€/kWh",
        "role": "value",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_SITE_PRICE],
        "nested": True,
    },
    {
        "id": "spot_price_mwh",
        "keys": ["spot_price_mwh", "spot_price"],
        "unit": "€/MWh",
        "role": "value",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_SITE_PRICE],
        "nested": True,
    },
    # PPS basics (read)
    {
        "id": "pps_battery_soc",
        "keys": ["battery_soc", "state_of_charge"],
        "unit": "%",
        "role": "value.battery",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },
    {
        "id": "pps_battery_soh",
        "keys": ["battery_soh", "state_of_health"],
        "unit": "%",
        "role": "value.battery",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    {
        "id": "pps_input_power",
        "keys": ["input_power", "ac_input_power"],
        "unit": "W",
        "role": "value.power",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },
    {
        "id": "pps_output_power",
        "keys": ["output_power", "ac_output_power"],
        "unit": "W",
        "role": "value.power",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },
    {
        "id": "pps_device_sn",
        "keys": ["device_sn"],
        "role": "text",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },
    {
        "id": "pps_input_limit_max",
        "keys": ["ac_input_limit_max"],
        "unit": "W",
        "role": "value.power",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_output_timeout_seconds", # disable (0), min:0, max: 86400, step 300
        "keys": ["ac_output_timeout_seconds"],
        "unit": "s",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_ac_input_limit", # AC charge limit: 100-1200 W, step: 100
        "keys": ["ac_input_limit"],
        "unit": "W",
        "role": "value.power",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_ac_frequency", # 60 / 50 Hz
        "keys": ["ac_frequency"],
        "unit": "Hz",
        "role": "value.power",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_ac_output_mode", # Normal (0), Smart (1) - auto-off below 14W
        "keys": ["ac_output_mode"],
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_dc_output_timeout_seconds", # disable (0), min:0, max: 86400, step 300
        "keys": ["dc_output_timeout_seconds"],
        "unit": "s",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_dc_12v_output_mode", # Normal (0), Smart (1) - auto-off below 3W
        "keys": ["dc_12v_output_mode"],
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_device_timeout_minutes", # 0 (Never), 30, 60, 120, 240, 360, 720, 1440
        "keys": ["device_timeout_minutes"],
        "unit": "m",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_display_timeout_seconds", # 0 (Never), 10, 30, 60, 300, 1800
        "keys": ["display_timeout_seconds"],
        "unit": "s",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_display_mode", # Low (1), Medium (2), High (3)
        "keys": ["display_mode"],
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_temp_unit_fahrenheit", # Celsius (0) or Fahrenheit (1)
        "keys": ["temp_unit_fahrenheit"],
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_ac_fast_charge_switch", # Ultrafast Charge switch: Disabled (0) or Enabled (1)
        "keys": ["ac_fast_charge_switch"],
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_display_switch", # Off (0), On (1)
        "keys": ["ac_display_switch"],
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_port_memory_switch", # Output Port Memory switch: Disabled (0) or Enabled (1)
        "keys": ["port_memory_switch"],
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_temperature",
        "keys": ["temperature"],
        "unit": "°",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_output_power_total",
        "keys": ["output_power_total"],
        "unit": "W",
        "role": "value.power",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_ac_output_power_switch", # Off (0), On (1)
        "keys": ["ac_output_power_switch"],
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_dc_input_power_switch", # Off (0), On (1)
        "keys": ["dc_input_power_switch"],
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_dc_input_power_total", # DC input power (solar + car charging)
        "keys": ["dc_input_power_total"],
        "unit": "W",
        "role": "value.power",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_usbc_1_status", # USB-C 1 status: Inactive (0), Discharging (1), Charging (2)
        "keys": ["usbc_1_status"],
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_usbc_1_power",
        "keys": ["usbc_1_power"],
        "unit": "W",
        "role": "value.power",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    }, 
    {
        "id": "pps_usbc_2_status",  # USB-C 2 status: Inactive (0), Discharging (1), Charging (2)
        "keys": ["usbc_2_status"],
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_usbc_2_power",
        "keys": ["usbc_2_power"],
        "unit": "W",
        "role": "value.power",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_usbc_3_status",  # USB-C 3 status: Inactive (0), Discharging (1), Charging (2)
        "keys": ["usbc_3_status"],
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_usbc_3_power",
        "keys": ["usbc_3_power"],
        "unit": "W",
        "role": "value.power",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_usba_1_status",  # USB-A 1 status: Inactive (0), Discharging (1), Charging (2)
        "keys": ["usba_1_status"],
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_usba_1_power",
        "keys": ["usba_1_power"],
        "unit": "W",
        "role": "value.power",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_dc_output_power_switch", # Off (0), On (1)
        "keys": ["dc_output_power_switch"],
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    {
        "id": "pps_dc_output_power_total", # Total Watt DC
        "keys": ["dc_output_power_total"],
        "unit": "W",
        "role": "value.power",
        "types": ["pps", "solarbank_pps", "powerbank"],
        "groups": [GROUP_PPS],
    },    
    
    # Smart plug
    {
        "id": "smartplug_power",
        "keys": ["power", "output_power"],
        "unit": "W",
        "role": "value.power",
        "types": [SMARTPLUG],
        "groups": [GROUP_SMARTPLUG],
    },
    {
        "id": "smartplug_energy_today",
        "keys": ["energy_today", "today_energy"],
        "unit": "kWh",
        "role": "value.energy",
        "types": [SMARTPLUG],
        "groups": [GROUP_SMARTPLUG, GROUP_ENERGY_DETAIL],
    },
    # EV charger (read / MQTT live)
    {
        "id": "evcharger_power",
        "keys": ["bat_charge_power", "power_l1", "output_power", "charge_power"],
        "unit": "W",
        "role": "value.power",
        "types": ["ev_charger", "charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "evcharger_status_desc",
        "keys": ["status_desc", "work_status_desc"],
        "role": "text",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_mode_status",
        "keys": ["ev_charger_mode_status"],
        "role": "value.mode",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_plug_status",
        "keys": ["plug_status"],
        "role": "indicator",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
        "kind": "boolean",
    },
    {
        "id": "ev_charger_status",
        "keys": ["ev_charger_status"],
        "role": "value",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_boost_status",
        "keys": ["boost_status"],
        "role": "indicator",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
        "kind": "boolean",
    },
    {
        "id": "ev_charger_bat_charge_power",
        "keys": ["bat_charge_power"],
        "unit": "W",
        "role": "value.power",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_charging_energy",
        "keys": ["charging_energy"],
        "unit": "kWh",
        "role": "value.energy",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_voltage_l1",
        "keys": ["voltage_l1"],
        "unit": "V",
        "role": "value.voltage",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_voltage_l2",
        "keys": ["voltage_l2"],
        "unit": "V",
        "role": "value.voltage",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_voltage_l3",
        "keys": ["voltage_l3"],
        "unit": "V",
        "role": "value.voltage",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_current_l1",
        "keys": ["current_l1"],
        "unit": "A",
        "role": "value.current",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_current_l2",
        "keys": ["current_l2"],
        "unit": "A",
        "role": "value.current",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_current_l3",
        "keys": ["current_l3"],
        "unit": "A",
        "role": "value.current",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_power_l1",
        "keys": ["power_l1"],
        "unit": "W",
        "role": "value.power",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_power_l2",
        "keys": ["power_l2"],
        "unit": "W",
        "role": "value.power",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_power_l3",
        "keys": ["power_l3"],
        "unit": "W",
        "role": "value.power",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_charging_energy_l1",
        "keys": ["charging_energy_l1"],
        "unit": "kWh",
        "role": "value.energy",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_charging_energy_l2",
        "keys": ["charging_energy_l2"],
        "unit": "kWh",
        "role": "value.energy",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_charging_energy_l3",
        "keys": ["charging_energy_l3"],
        "unit": "kWh",
        "role": "value.energy",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_plug_countdown_seconds",
        "keys": ["plug_countdown_seconds"],
        "unit": "s",
        "role": "value.interval",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_start_countdown_seconds",
        "keys": ["start_countdown_seconds"],
        "unit": "s",
        "role": "value.interval",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_charging_duration_seconds",
        "keys": ["charging_duration_seconds"],
        "unit": "s",
        "role": "value.interval",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_charging_window_seconds",
        "keys": ["charging_window_seconds"],
        "unit": "s",
        "role": "value.interval",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_ocpp_connect_status",
        "keys": ["ocpp_connect_status"],
        "role": "value",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_cp_signal_status",
        "keys": ["cp_signal_status"],
        "role": "value",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_sw_version",
        "keys": ["sw_version"],
        "role": "text",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER, GROUP_DIAGNOSTICS],
    },
    {
        "id": "ev_charger_hw_version",
        "keys": ["hw_version"],
        "role": "text",
        "types": ["ev_charger"],
        "groups": [GROUP_EV_CHARGER, GROUP_DIAGNOSTICS],
    },
    # HES / power panel (minimal)
    {
        "id": "hes_grid_power",
        "keys": ["grid_power", "grid_import_power"],
        "unit": "W",
        "role": "value.power",
        "types": ["hes", "home_backup"],
        "groups": [GROUP_HES],
    },
    {
        "id": "powerpanel_avg_power",
        "keys": ["avg_power", "average_power"],
        "unit": "W",
        "role": "value.power",
        "types": ["powerpanel"],
        "groups": [GROUP_POWER_PANEL],
    },
]

EXTENDED_CONTROL_ENTITIES: list[dict[str, Any]] = [
    {
        "id": "ev_charger_mode",
        "keys": ["ev_charger_mode"],
        "role": "value.mode",
        "types": ["ev_charger"],
        "control": "ev_charger_mode",
        "kind": "list",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_schedule_switch",
        "keys": ["schedule_switch"],
        "role": "switch",
        "types": ["ev_charger"],
        "control": "ev_charger_schedule_switch",
        "kind": "switch",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_schedule_mode",
        "keys": ["schedule_mode"],
        "role": "value.mode",
        "types": ["ev_charger"],
        "control": "ev_charger_schedule_mode",
        "kind": "list",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_week_start_time",
        "keys": ["week_start_time"],
        "role": "text",
        "types": ["ev_charger"],
        "control": "ev_charger_week_start_time",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_week_end_time",
        "keys": ["week_end_time"],
        "role": "text",
        "types": ["ev_charger"],
        "control": "ev_charger_week_end_time",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_weekend_start_time",
        "keys": ["weekend_start_time"],
        "role": "text",
        "types": ["ev_charger"],
        "control": "ev_charger_weekend_start_time",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_weekend_end_time",
        "keys": ["weekend_end_time"],
        "role": "text",
        "types": ["ev_charger"],
        "control": "ev_charger_weekend_end_time",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_weekend_mode",
        "keys": ["weekend_mode"],
        "role": "value.mode",
        "types": ["ev_charger"],
        "control": "ev_charger_weekend_mode",
        "kind": "list",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_auto_start_switch",
        "keys": ["auto_start_switch"],
        "role": "switch",
        "types": ["ev_charger"],
        "control": "ev_charger_auto_start_switch",
        "kind": "switch",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_auto_charge_restart_switch",
        "keys": ["auto_charge_restart_switch"],
        "role": "switch",
        "types": ["ev_charger"],
        "control": "ev_charger_auto_charge_restart_switch",
        "kind": "switch",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_random_delay_switch",
        "keys": ["random_delay_switch"],
        "role": "switch",
        "types": ["ev_charger"],
        "control": "ev_charger_random_delay_switch",
        "kind": "switch",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_max_current",
        "keys": ["max_evcharge_current"],
        "role": "level.current",
        "types": ["ev_charger"],
        "control": "ev_charger_max_current",
        "kind": "number",
        "min": 6,
        "max": 32,
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_solar_switch",
        "keys": ["solar_evcharge_switch"],
        "role": "switch",
        "types": ["ev_charger"],
        "control": "ev_charger_solar_switch",
        "kind": "switch",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_solar_mode",
        "keys": ["solar_evcharge_mode"],
        "role": "value.mode",
        "types": ["ev_charger"],
        "control": "ev_charger_solar_mode",
        "kind": "list",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_solar_min_current",
        "keys": ["solar_evcharge_min_current"],
        "role": "level.current",
        "types": ["ev_charger"],
        "control": "ev_charger_solar_min_current",
        "kind": "number",
        "min": 6,
        "max": 32,
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_phase_mode",
        "keys": ["phase_operating_mode"],
        "role": "value.mode",
        "types": ["ev_charger"],
        "control": "ev_charger_phase_mode",
        "kind": "list",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_auto_phase_switch",
        "keys": ["auto_phase_switch"],
        "role": "switch",
        "types": ["ev_charger"],
        "control": "ev_charger_auto_phase_switch",
        "kind": "switch",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_load_balance_switch",
        "keys": ["load_balance_switch"],
        "role": "switch",
        "types": ["ev_charger"],
        "control": "ev_charger_load_balance_switch",
        "kind": "switch",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_main_breaker_limit",
        "keys": ["main_breaker_limit"],
        "role": "level.current",
        "types": ["ev_charger"],
        "control": "ev_charger_main_breaker_limit",
        "kind": "number",
        "min": 10,
        "max": 500,
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_load_balance_monitor_device",
        "keys": ["load_balance_monitor_device"],
        "role": "text",
        "types": ["ev_charger"],
        "control": "ev_charger_load_balance_monitor_device",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_solar_monitor_switch",
        "keys": ["solar_evcharge_monitoring_mode"],
        "role": "switch",
        "types": ["ev_charger"],
        "control": "ev_charger_solar_monitor_switch",
        "kind": "switch",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_solar_monitor_device",
        "keys": ["solar_evcharge_monitor_device"],
        "role": "text",
        "types": ["ev_charger"],
        "control": "ev_charger_solar_monitor_device",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_restart",
        "keys": [],
        "role": "switch",
        "types": ["ev_charger"],
        "control": "ev_charger_restart",
        "kind": "switch",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_plug_lock_switch",
        "keys": ["plug_lock_switch"],
        "role": "switch",
        "types": ["ev_charger"],
        "control": "ev_charger_plug_lock_switch",
        "kind": "switch",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_light_brightness",
        "keys": ["light_brightness"],
        "role": "level",
        "types": ["ev_charger"],
        "control": "ev_charger_light_brightness",
        "kind": "number",
        "min": 0,
        "max": 100,
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_light_off_schedule_switch",
        "keys": ["light_off_schedule_switch"],
        "role": "switch",
        "types": ["ev_charger"],
        "control": "ev_charger_light_off_schedule_switch",
        "kind": "switch",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_light_off_start_time",
        "keys": ["light_off_start_time"],
        "role": "text",
        "types": ["ev_charger"],
        "control": "ev_charger_light_off_start_time",
        "kind": "text",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_light_off_end_time",
        "keys": ["light_off_end_time"],
        "role": "text",
        "types": ["ev_charger"],
        "control": "ev_charger_light_off_end_time",
        "kind": "text",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_smart_touch_mode",
        "keys": ["smart_touch_mode"],
        "role": "value.mode",
        "types": ["ev_charger"],
        "control": "ev_charger_smart_touch_mode",
        "kind": "list",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_modbus_switch",
        "keys": ["modbus_switch"],
        "role": "switch",
        "types": ["ev_charger"],
        "control": "ev_charger_modbus_switch",
        "kind": "switch",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_wipe_up_mode",
        "keys": ["wipe_up_mode"],
        "role": "value.mode",
        "types": ["ev_charger"],
        "control": "ev_charger_wipe_up_mode",
        "kind": "list",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "ev_charger_wipe_down_mode",
        "keys": ["wipe_down_mode"],
        "role": "value.mode",
        "types": ["ev_charger"],
        "control": "ev_charger_wipe_down_mode",
        "kind": "list",
        "groups": [GROUP_EV_CHARGER],
    },
    {
        "id": "preset_discharge_priority",
        "keys": ["preset_discharge_priority", "priority_discharge_switch"],
        "role": "switch",
        "types": [SOLARBANK, COMBINER],
        "control": "preset_discharge_priority",
        "groups": [GROUP_ADVANCED_CONTROLS],
    },
    {
        "id": "preset_backup_option",
        "keys": ["preset_backup_option", "backup_option"],
        "role": "switch",
        "types": [SOLARBANK, COMBINER],
        "control": "preset_backup_option",
        "groups": [GROUP_ADVANCED_CONTROLS],
    },
    {
        "id": "preset_charge_priority",
        "keys": ["preset_charge_priority", "charge_priority", "default_charge_priority"],
        "role": "level",
        "types": [SOLARBANK, COMBINER],
        "control": "preset_charge_priority",
        "min": 0,
        "max": 100,
        "groups": [GROUP_ADVANCED_CONTROLS],
    },
    {
        "id": "preset_device_output_power",
        "keys": ["preset_device_output_power", "device_output_power"],
        "role": "level.power",
        "types": [SOLARBANK],
        "control": "preset_device_output_power",
        "min": 0,
        "max": 1200,
        "groups": [GROUP_ADVANCED_CONTROLS],
    },
    {
        "id": "max_soc",
        "keys": ["max_soc", "soc_max"],
        "role": "level.battery",
        "types": [SOLARBANK, COMBINER],
        "control": "max_soc",
        "min": 0,
        "max": 100,
        "groups": [GROUP_ADVANCED_CONTROLS],
    },
    {
        "id": "backup_soc",
        "keys": ["backup_soc", "soc_backup"],
        "role": "level.battery",
        "types": [SOLARBANK, COMBINER],
        "control": "backup_soc",
        "min": 0,
        "max": 100,
        "groups": [GROUP_ADVANCED_CONTROLS],
    },
    {
        "id": "auto_upgrade",
        "keys": ["auto_upgrade", "auto_upgrade_switch"],
        "role": "switch",
        "types": [SOLARBANK, COMBINER, SMARTPLUG],
        "control": "auto_upgrade",
        "groups": [GROUP_ADVANCED_CONTROLS],
    },
    # PPS switches (MQTT when available)
    {
        "id": "ac_output_power_switch",
        "keys": ["ac_output_power_switch", "ac_output_switch"],
        "role": "switch",
        "types": ["pps", "solarbank_pps"],
        "control": "ac_output_power_switch",
        "groups": [GROUP_PPS],
    },
    {
        "id": "ac_fast_charge_switch_pps",
        "keys": ["ac_charge_switch", "ac_fast_charge_switch"],
        "role": "switch",
        "types": ["pps"],
        "control": "ac_fast_charge_switch",
        "groups": [GROUP_PPS],
    },
]

# Extra daily energy statistics (energy_detail group)
EXTENDED_ENERGY_STATISTICS: list[dict[str, Any]] = [
    {
        "id": "daily_solar_to_grid",
        "keys": ["solar_to_grid"],
        "unit": "kWh",
        "types": [SYSTEM, SITE, SOLARBANK, COMBINER],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_solar_production_pv1",
        "keys": ["solar_production_pv1", "pv1_production"],
        "unit": "kWh",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_solar_production_pv2",
        "keys": ["solar_production_pv2", "pv2_production"],
        "unit": "kWh",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_solar_production_pv3",
        "keys": ["solar_production_pv3", "pv3_production"],
        "unit": "kWh",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_solar_production_pv4",
        "keys": ["solar_production_pv4", "pv4_production"],
        "unit": "kWh",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_solar_production_inverter",
        "keys": ["solar_production_inverter", "inverter_production"],
        "unit": "kWh",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_solar_share",
        "keys": ["solar_share"],
        "unit": "%",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_battery_share",
        "keys": ["battery_share"],
        "unit": "%",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_grid_share",
        "keys": ["grid_share"],
        "unit": "%",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_ac_socket",
        "keys": ["ac_socket", "ac_socket_energy"],
        "unit": "kWh",
        "types": [SYSTEM, SITE, SOLARBANK],
        "groups": [GROUP_ENERGY_DETAIL],
    },
    {
        "id": "daily_smartplugs_total",
        "keys": ["smartplugs_total", "smartplug_total"],
        "unit": "kWh",
        "types": [SYSTEM, SITE],
        "groups": [GROUP_ENERGY_DETAIL, GROUP_SMARTPLUG],
    },
]

EXTENDED_STATISTICS_LABELS_DE: dict[str, str] = {
    "daily_solar_to_grid": "Solar → Netz (heute)",
    "daily_solar_production_pv1": "PV1 Ertrag (heute)",
    "daily_solar_production_pv2": "PV2 Ertrag (heute)",
    "daily_solar_production_pv3": "PV3 Ertrag (heute)",
    "daily_solar_production_pv4": "PV4 Ertrag (heute)",
    "daily_solar_production_inverter": "WR Ertrag (heute)",
    "daily_solar_share": "Solar-Anteil (heute)",
    "daily_battery_share": "Batterie-Anteil (heute)",
    "daily_grid_share": "Netz-Anteil (heute)",
    "daily_ac_socket": "AC-Steckdose (heute)",
    "daily_smartplugs_total": "Steckdosen gesamt (heute)",
}
